#!/usr/bin/env ruby

tips = [
  'Tip 1 │  Meet the Dot Command',
  'Tip 2 │  Don’t Repeat Yourself',
  'Tip 3 │  Take One Step Back, Then Three Forward',
  'Tip 4 │  Act, Repeat, Reverse',
  'Tip 5 │  Find and Replace by Hand',
  'Tip 6 │  Meet the Dot Formula',
  'Tip 7 │  Pause with Your Brush Off the Page',
  'Tip 8 │  Chunk Your Undos',
  'Tip 9 │  Compose Repeatable Changes',
  'Tip 10 │  Use Counts to Do Simple Arithmetic',
  'Tip 11 │  Don’t Count If You Can Repeat',
  'Tip 12 │  Combine and Conquer',
  'Tip 13 │  Make Corrections Instantly from Insert Mode',
  'Tip 14 │  Get Back to Normal Mode',
  'Tip 15 │  Paste from a Register Without Leaving Insert Mode',
  'Tip 16 │  Do Back-of-the-Envelope Calculations in Place',
  'Tip 17 │  Insert Unusual Characters by Character Code',
  'Tip 18 │  Insert Unusual Characters by Digraph',
  'Tip 19 │  Overwrite Existing Text with Replace Mode',
  'Tip 20 │  Grok Visual Mode',
  'Tip 21 │  Define a Visual Selection',
  'Tip 22 │  Repeat Line-Wise Visual Commands',
  'Tip 23 │  Prefer Operators to Visual Commands Where Possible',
  'Tip 24 │  Edit Tabular Data with Visual-Block Mode',
  'Tip 25 │  Change Columns of Text',
  'Tip 26 │  Append After a Ragged Visual Block',
  'Tip 27 │  Meet Vim’s Command Line',
  'Tip 28 │  Execute a Command on One or More Consecutive Lines',
  'Tip 29 │  Duplicate or Move Lines Using ‘:t’ and ‘:m’ Commands',
  'Tip 30 │  Run Normal Mode Commands Across a Range',
  'Tip 31 │  Repeat the Last Ex Command',
  'Tip 32 │  Tab-Complete Your Ex Commands',
  'Tip 33 │  Insert the Current Word at the Command Prompt',
  'Tip 34 │  Recall Commands from History',
  'Tip 35 │  Run Commands in the Shell',
  'Tip 36 │  Run Multiple Ex Commands as a Batch',
  'Tip 37 │  Track Open Files with the Buffer List',
  'Tip 38 │  Group Buffers into a Collection with the Argument List',
  'Tip 39 │  Manage Hidden Files',
  'Tip 40 │  Divide Your Workspace into Split Windows',
  'Tip 41 │  Organize Your Window Layouts with Tab Pages',
  'Tip 42 │  Open a File by Its Filepath Using ‘:edit',
  'Tip 43 │  Open a File by Its Filename Using ‘:find',
  'Tip 44 │  Explore the File System with netrw',
  'Tip 45 │  Save Files to Nonexistent Directories',
  'Tip 46 │  Save a File as the Super User',
  'Tip 47 │  Keep Your Fingers on the Home Row',
  'Tip 48 │  Distinguish Between Real Lines and Display Lines',
  'Tip 49 │  Move Word-Wise',
  'Tip 50 │  Find by Character',
  'Tip 51 │  Search to Navigate',
  'Tip 52 │  Trace Your Selection with Precision Text Objects',
  'Tip 53 │  Delete Around, or Change Inside',
  'Tip 54 │  Mark Your Place and Snap Back to It',
  'Tip 55 │  Jump Between Matching Parentheses',
  'Tip 56 │  Traverse the Jump List',
  'Tip 57 │  Traverse the Change List',
  'Tip 58 │  Jump to the Filename Under the Cursor',
  'Tip 59 │  Snap Between Files Using Global Marks',
  'Tip 60 │  Delete, Yank, and Put with Vim’s Unnamed Register',
  'Tip 61 │  Grok Vim’s Registers',
  'Tip 62 │  Replace a Visual Selection with a Register',
  'Tip 63 │  Paste from a Register',
  'Tip 64 │  Interact with the System Clipboard',
  'Tip 65 │  Record and Execute a Macro',
  'Tip 66 │  Normalize, Strike, Abort',
  'Tip 67 │  Play Back with a Count',
  'Tip 68 │  Repeat a Change on Contiguous Lines',
  'Tip 69 │  Append Commands to a Macro',
  'Tip 70 │  Act Upon a Collection of Files',
  'Tip 71 │  Evaluate an Iterator to Number Items in a List',
  'Tip 72 │  Edit the Contents of a Macro',
  'Tip 73 │  Tune the Case Sensitivity of Search Patterns',
  'Tip 74 │  Use the \v Pattern Switch for Regex Searches',
  'Tip 75 │  Use the \V Literal Switch for Verbatim Searches',
  'Tip 76 │  Use Parentheses to Capture Submatches',
  'Tip 77 │  Stake the Boundaries of a Word',
  'Tip 78 │  Stake the Boundaries of a Match',
  'Tip 79 │  Escape Problem Characters'
]

puts ARGV[0] ? tips[ARGV[0].to_i] : tips.sample
